import { authorizeManagerRequest } from './manager-auth.js';
import { handleManagerCommand, flushManagerOutbox, managerV2Enabled } from './manager-runtime.js';
import { createManualOrder } from './manager-intake.js';
import { searchHistory, getHistoryDetail, formatCustomerHistory } from './manager-history.js';

const json=(body,status=200)=>new Response(JSON.stringify(body),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'}});
const query=async(env,sql,...args)=>(await env.DB.prepare(sql).bind(...args).all()).results||[];
export async function managerApi(request,env) {
  const auth=await authorizeManagerRequest(request,env);if(auth.denied)return auth.denied;
  if(!managerV2Enabled(env))return json({error:'new_manager_not_enabled'},409);
  const url=new URL(request.url);
  if(request.method==='GET'&&url.pathname==='/api/manager/history') {
    const offset=Math.max(0,Math.min(10000,Number.parseInt(url.searchParams.get('offset')||'0',10)||0));
    return json(await searchHistory((url.searchParams.get('q')||'').trim().slice(0,100),env,{limit:20,offset,allowEmpty:true}));
  }
  if(request.method==='GET'&&url.pathname==='/api/manager/history-detail') {
    const detail=await getHistoryDetail(url.searchParams.get('id')||'',env);
    return detail?json({detail}):json({error:'not_found'},404);
  }
  if(request.method==='GET' && url.pathname==='/api/manager/orders') {
    const search=(url.searchParams.get('q')||'').trim().slice(0,100);
    const searchSql=search?`WHERE instr(lower(o.title || ' ' || o.id),lower(?))>0 OR EXISTS (SELECT 1 FROM manager_fields f WHERE f.order_id=o.id AND f.field_key IN ('customer_name','phone','receive_date','delivery_address') AND instr(lower(f.value_text),lower(?))>0)`:'';
    const orders=await query(env,`SELECT o.* FROM manager_orders o ${searchSql} ORDER BY o.updated_at DESC LIMIT 100`,...(search?[search,search]:[]));
    const today=new Date(Date.now()+9*60*60*1000).toISOString().slice(0,10);
    const handoffs=await query(env,`SELECT o.* FROM manager_orders o JOIN manager_fields f ON f.order_id=o.id AND f.field_key='receive_date' WHERE o.status='open' AND o.fulfillment_status!='fulfilled' AND f.value_text=? ORDER BY o.updated_at`,today);
    const replyCount=await query(env,`SELECT COUNT(*) AS count FROM manager_drafts WHERE status IN ('pending','held')`);
    const tasks=await query(env,`SELECT * FROM manager_tasks WHERE status='open' ORDER BY due_at LIMIT 100`);
    const failures=await query(env,`SELECT id,channel,status,last_error,created_at FROM manager_outbox WHERE status IN ('failed','uncertain') ORDER BY created_at DESC LIMIT 30`);
    const drafts=await query(env,`SELECT id,customer_id,message,source_event_id FROM manager_drafts WHERE order_id IS NULL AND status='pending' ORDER BY created_at LIMIT 30`);
    return json({orders,tasks,failures,routing:drafts,sendPaused:env.MANAGER_SEND_PAUSED==='true',today:{date:today,handoffs,replyCount:replyCount[0].count},limited:orders.length===100});
  }
  if(request.method==='POST'&&url.pathname==='/api/manager/intake') {
    const body=await request.text();if(body.length>12000)return json({error:'too_large'},413);
    let data;try{data=JSON.parse(body);}catch{return json({error:'invalid_json'},400);}
    try{return json(await createManualOrder(data,auth.actor,env));}catch(error){if(error.code==='invalid_intake')return json({error:error.message},error.status||400);throw error;}
  }
  if(request.method==='GET'&&url.pathname==='/api/manager/order') {
    const orderId=url.searchParams.get('id');
    if(!/^M[A-F0-9]{16}$/.test(orderId||''))return json({error:'invalid_order'},400);
    const order=(await query(env,`SELECT * FROM manager_orders WHERE id=?`,orderId))[0];
    if(!order)return json({error:'not_found'},404);
    const fields=await query(env,`SELECT * FROM manager_fields WHERE order_id=?`,orderId);
    const items=await query(env,`SELECT * FROM manager_order_items WHERE order_id=?`,orderId);
    const drafts=await query(env,`SELECT * FROM manager_drafts WHERE order_id=? ORDER BY created_at DESC LIMIT 20`,orderId);
    const changes=await query(env,`SELECT * FROM manager_changes WHERE order_id=? AND status='pending'`,orderId);
    const events=await query(env,`SELECT * FROM manager_events WHERE order_id=? ORDER BY occurred_at DESC LIMIT 100`,orderId);
    const history=await query(env,`SELECT id,source_heading,raw_text,review_status FROM manager_imports WHERE linked_customer_id=?`,order.customer_id);
    const pastInfo=await formatCustomerHistory(order.customer_id,env,order.id);
    return json({order,fields,items,drafts,changes,events,history,pastInfo,historyLimit:100});
  }
  if(request.method==='GET'&&url.pathname==='/api/manager/imports') {
    return json({imports:await query(env,`SELECT id,source_heading,source_line,review_status,linked_customer_id FROM manager_imports ORDER BY source_file,source_line`)});
  }
  if(request.method==='POST'&&url.pathname==='/api/manager/command') {
    const body=await request.text();if(body.length>12000)return json({error:'too_large'},413);
    let data;try{data=JSON.parse(body);}catch{return json({error:'invalid_json'},400);}
    if(typeof data.command!=='string'||data.command.length>6000)return json({error:'invalid_command'},400);
    const result=await handleManagerCommand(data.command,auth.actor,env);
    if(result===null)return json({error:'unknown_command'},400);
    await flushManagerOutbox(env);
    return json({message:result});
  }
  if(request.method==='POST'&&url.pathname==='/api/manager/import') {
    const text=await request.text();if(text.length>1_000_000)return json({error:'too_large'},413);
    let data;try{data=JSON.parse(text);}catch{return json({error:'invalid_json'},400);}
    if(data.schema_version!==1||data.target!=='manager_imports'||!Array.isArray(data.records)||data.records.length>200)return json({error:'invalid_bundle'},400);
    const batch=[];
    for(const row of data.records) {
      if(!/^legacy_[a-f0-9]{32}$/.test(row.id||'')||typeof row.raw_text!=='string'||row.raw_text.length>20000||typeof row.source_heading!=='string'||!Number.isInteger(row.source_line)||row.source_line<1||row.source_file!=='CUSTOMER_ORDER_CARDS_PRIVATE.md')return json({error:'invalid_record'},400);
      const digest=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(row.raw_text))),b=>b.toString(16).padStart(2,'0')).join('');
      if(digest!==row.source_hash)return json({error:'source_hash_mismatch'},400);
      // Caller-supplied link/approval fields are deliberately ignored.
      batch.push(env.DB.prepare(`INSERT OR IGNORE INTO manager_imports(id,source_hash,source_file,source_heading,source_line,raw_text,review_status,created_at) VALUES (?,?,?,?,?,?,'needs_review',?)`)
        .bind(row.id,row.source_hash,row.source_file,row.source_heading,row.source_line,row.raw_text,new Date().toISOString()));
    }
    if(batch.length)await env.DB.batch(batch);
    return json({staged:data.records.length,activated:0});
  }
  return json({error:'not_found'},404);
}

export function managerConsole() {
  return new Response(HTML,{headers:{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store',
    'Content-Security-Policy':"default-src 'none'; script-src 'self' 'unsafe-inline'; style-src 'unsafe-inline'; connect-src 'self'; img-src 'self'; manifest-src 'self'; worker-src 'self'; frame-ancestors 'none'; base-uri 'none'; form-action 'none'",
    'X-Content-Type-Options':'nosniff','Referrer-Policy':'no-referrer'}});
}

const HTML=String.raw`<!doctype html><html lang="ja"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>elm・balloon 統括ノート</title>
<link rel="manifest" href="/manager.webmanifest"><meta name="theme-color" content="#285c48"><meta name="apple-mobile-web-app-capable" content="yes"><meta name="apple-mobile-web-app-title" content="統括ノート"><link rel="icon" href="/manager-icon.svg"><link rel="apple-touch-icon" href="/manager-icon.svg">
<style>body{margin:0;background:#f6f5f0;color:#273c35;font:16px/1.7 system-ui,sans-serif}header,main{max-width:1050px;margin:auto;padding:24px}header{display:flex;justify-content:space-between;align-items:center}h1{font-size:24px;margin:0}h2{font-size:20px}button,input,textarea,select{font:inherit;border:1px solid #bac8bf;border-radius:8px;padding:10px}button{background:#fff;color:#254b3d;cursor:pointer;margin:4px}button.primary{background:#285c48;color:white}input,textarea{box-sizing:border-box;max-width:100%}textarea{width:100%;min-height:110px}section,.card{background:white;border:1px solid #dbe0d8;padding:20px;border-radius:14px;margin:14px 0}.grid{display:grid;grid-template-columns:1fr 1.5fr;gap:20px}.muted{color:#5e6a64;font-size:14px}.warn{background:#fff2d7;border-left:4px solid #bd8730;padding:12px}.stack{white-space:pre-wrap;overflow-wrap:anywhere}label{display:block;margin:10px 0}button:focus-visible,input:focus-visible,textarea:focus-visible{outline:3px solid #b48842;outline-offset:2px}.hidden{display:none}#status{white-space:pre-wrap}dl{display:grid;grid-template-columns:130px 1fr}dt,dd{margin:0;padding:8px;border-bottom:1px solid #eee}@media(max-width:700px){.grid{display:block}header,main{padding:15px}dl{display:block}}</style>
<header><div><h1>elm・balloon 統括ノート</h1><div class="muted">ご相談から、お渡し・入金・回収まで</div></div><button id="logout" class="hidden">接続を終了</button></header>
<style>header{position:sticky;top:0;background:#f6f5f0;z-index:2}button{min-height:46px}nav{display:flex;gap:8px;position:sticky;bottom:0;background:#f6f5f0;padding:10px 0 calc(10px + env(safe-area-inset-bottom));z-index:2}nav button{flex:1}.install{font-size:14px;background:#e7eee7;padding:12px;border-radius:8px}@media(max-width:700px){header h1{font-size:19px}body[data-view=detail] .grid>div:first-child{display:none}body:not([data-view=detail]) #detail{display:none}#status{max-height:40vh;overflow:auto}main{padding-bottom:80px}nav{position:fixed;left:0;right:0;bottom:0;padding-left:10px;padding-right:10px}}</style>
<main><section id="login"><h2>スマートフォンで注文を確認</h2><p>店長用LINEへ「統括アプリ」と送ると、専用の入口が届きます。</p><p class="install">SafariやChromeで開き、「ホーム画面に追加」すると、次回からアイコンで開けます。</p><details><summary>設定・開発用の接続</summary><label>管理用キー <input id="token" type="password" autocomplete="off"></label><button id="connect" class="primary">開く</button></details></section><div id="status" role="status" aria-live="polite"></div><div id="app" class="hidden"><div id="mode"></div><button id="install" class="hidden">ホーム画面に追加</button><button id="refresh">最新の状態に更新</button><button id="importToggle">過去カルテの取込み・確認</button><section id="imports" class="hidden"><label>取込資料 <input type="file" id="bundle" accept=".json"></label><button id="upload">確認待ち資料として取り込む</button><div id="importList"></div></section><section id="historyTalk"><h2>統括に過去の注文を尋ねる</h2><label>確認したいこと <textarea id="historyQuestion" placeholder="例：山田さんの過去の注文を確認したい" maxlength="200"></textarea></label><button id="historyAsk">統括に確認</button><label>過去カルテを検索 <input id="historyQuery" placeholder="お名前・電話・商品"></label><button id="historySearch">候補を探す</button><div id="historyResults"></div><div id="historyAnswer" class="stack" role="status"></div><button id="historyMore" class="hidden">次の候補</button><p class="muted">過去の記録です。現在の価格・在庫・住所は改めて確認します。名前が一致しても本人とは断定しません。</p></section><section id="workday"><h2>今日やること</h2><div id="today"></div></section><section><label>注文を検索 <input id="search" placeholder="名前・電話番号・日付・案件名"></label><button id="searchButton">検索</button><button id="clearSearch">全件に戻す</button><details><summary>電話・来店の新しい注文を登録</summary><label>受付方法 <select id="intakeChannel"><option value="phone">電話</option><option value="walkin">来店</option></select></label><label>案件名（必須） <input id="intakeTitle" maxlength="120"></label><label>お名前 <input id="intakeName" maxlength="120"></label><label>電話番号 <input id="intakePhone" maxlength="40" type="tel"></label><label>相談内容 <textarea id="intakeMemo" maxlength="4000"></textarea></label><button id="intakeSave">カルテを作成</button></details></section><div class="grid"><div><h2>対応が必要な注文</h2><div id="orders"></div><h2>期限・送信の確認</h2><div id="tasks"></div></div><div id="detail"><section>注文を選ぶと、内容と次の対応が表示されます。</section></div></div><nav aria-label="アプリの操作"><button id="navOrders">注文一覧</button><button id="navTasks">対応待ち</button><button id="navDetail">カルテ</button></nav></div></main>
<script>
let key='',selected=null;const $=id=>document.getElementById(id);const labels={purpose:'用途',product_type:'商品',product_source:'参考商品',receive_date:'受取希望日',use_date:'使用日',receive_time:'受取時間',fulfillment_method:'受取方法',delivery_area:'配達地域',delivery_address:'お届け先',quantity:'数量',budget:'予算',budget_scope:'予算の単位',color_vibe:'色・雰囲気',customer_name:'お名前',phone:'電話番号',balloon_message:'文字入れ',card_message:'カード'};
const states={open:'進行中',closed:'終了',consulting:'相談中',production:'制作中',ready:'完成',pending:'確認待ち',fulfilled:'受渡し済み',unconfirmed:'未確認',paid:'入金済み',collected:'回収済み',not_required:'回収不要',instructed:'支払案内済み',awaiting_confirmation:'支払確認待ち'};
function el(tag,text,cls){const node=document.createElement(tag);if(text!==undefined)node.textContent=text;if(cls)node.className=cls;return node}function button(text,fn){const b=el('button',text);b.onclick=async()=>{b.disabled=true;try{await fn()}catch(e){$('status').textContent=e.message}finally{b.disabled=false}};return b}
async function api(path,body){if(!navigator.onLine)throw new Error('通信できません。接続が戻ってから操作してください。注文情報は端末に保存していません。');const r=await fetch('/api/manager/'+path,{method:body?'POST':'GET',credentials:'same-origin',headers:{...(key?{Authorization:'Bearer '+key}:{}),'X-Manager-Request':'1',...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined});const data=await r.json();if(!r.ok)throw new Error(data.error==='unauthorized'?'店長用LINEから「統括アプリ」で開き直してください。':data.error==='expired_or_used_link'?'この入口は期限切れか使用済みです。LINEで「統括アプリ」と送ってください。':'処理できませんでした：'+data.error);return data}
async function command(text){const data=await api('command',{command:text});$('status').textContent=data.message;await refresh();if(selected)await show(selected)}
function fieldEditor(orderId,fields){const box=el('div');box.append(el('h3','項目の追加・訂正'));const choice=el('select');choice.setAttribute('aria-label','変更する項目');for(const [key,label] of Object.entries(labels)){const option=el('option',label);option.value=key;choice.append(option)}const value=el('textarea');value.setAttribute('aria-label','項目の内容');value.placeholder='内容を入力してください';const fill=()=>{value.value=fields.find(f=>f.field_key===choice.value)?.value_text||''};choice.onchange=fill;fill();box.append(choice,value,el('p','店長確認済みの内容として保存します。変更すると以前の返信案は再確認が必要です。','muted'),button('内容を確認して保存',async()=>{const text=value.value.trim();if(!text)throw new Error('項目の内容を入力してください。');await command('項目確定 '+orderId+' '+choice.value+'：'+text)}));return box}
async function refresh(){const d=await api('orders?q='+encodeURIComponent($('search').value.trim()));$('mode').textContent=d.sendPaused?'送信は停止中です。カルテと返信案の確認を進められます。':'承認した返信だけを送信します。';$('mode').className=d.sendPaused?'warn':'muted';renderToday(d);$('orders').replaceChildren();if(!d.orders.length)$('orders').append(el('p','該当する注文はありません。'));if(d.limited)$('orders').append(el('p','最新100件を表示しています。検索で絞り込んでください。','warn'));for(const o of d.orders){const c=el('section');c.append(el('strong',o.title),el('div',o.id,'muted'),el('p','制作：'+(states[o.production_status]||o.production_status)+'／受渡：'+(states[o.fulfillment_status]||o.fulfillment_status)+'／支払：'+(states[o.payment_status]||o.payment_status)),button('内容を確認',()=>show(o.id)));$('orders').append(c)}$('tasks').replaceChildren();for(const t of d.tasks)$('tasks').append(el('p',t.detail+'\n'+new Date(t.due_at).toLocaleString('ja-JP'),'stack'));for(const f of d.failures)$('tasks').append(el('p','送信の確認が必要：'+f.status+' '+f.last_error,'warn'));for(const r of d.routing){const c=el('section');c.append(el('strong','注文の振分待ち'),el('p',r.message,'stack'),button('確認文を送信',()=>command('承認送信 '+r.id)));for(const o of d.orders.filter(o=>o.customer_id===r.customer_id&&o.status==='open'))c.append(button(o.title+' に紐付ける',()=>command('振分 '+r.source_event_id+' '+o.id)));$('tasks').append(c)}}
function renderToday(d){const root=$('today');root.replaceChildren();const overdue=d.tasks.filter(t=>Date.parse(t.due_at)<Date.now());root.append(el('p',d.today.date+'／返信確認 '+d.today.replyCount+'件／期限超過 '+overdue.length+'件'));for(const o of d.today.handoffs)root.append(button('本日お渡し：'+o.title,()=>show(o.id)));if(!d.today.handoffs.length)root.append(el('p','本日のお渡し予定はありません。','muted'));for(const t of overdue)root.append(button('期限超過：'+t.detail,()=>t.order_id?show(t.order_id):Promise.resolve()));}
let intakeRequestId=null;
let historyOffset=0,historySearchValue='';
async function searchPast(reset=true){if(reset){historyOffset=0;historySearchValue=$('historyQuery').value.trim();$('historyResults').replaceChildren()}const data=await api('history?q='+encodeURIComponent(historySearchValue)+'&offset='+historyOffset);for(const row of data.records){const box=el('section');box.append(el('strong',row.label),el('p',row.summary,'stack'),el('p','確認状態：'+row.reviewStatus,'muted'),button('過去の内容を読む',async()=>{const d=await api('history-detail?id='+encodeURIComponent(row.id));$('historyAnswer').textContent=d.detail}));if(row.kind==='import')box.append(button('選択中の注文のお客様と照合',async()=>{if(!selected)throw new Error('先に現在の注文を選んでください。');const d=await api('command',{command:'履歴紐付 '+selected+' '+row.id});$('historyAnswer').textContent=d.message}),button('本文と本人を確認済みとして保存',async()=>{if(!selected)throw new Error('先に現在の注文を選んでください。');const d=await api('command',{command:'履歴承認 '+selected+' '+row.id});$('historyAnswer').textContent=d.message;await show(selected)}));$('historyResults').append(box)}if(!data.records.length)$('historyResults').append(el('p','一致する保存済み過去カルテはありません。'));historyOffset+=data.records.length;$('historyMore').classList.toggle('hidden',!data.hasMore)}
$('historyAsk').onclick=async()=>{try{const text=$('historyQuestion').value.trim();if(!text)throw new Error('お名前など確認したい内容を入力してください。');const d=await api('command',{command:text});$('historyAnswer').textContent=d.message}catch(e){$('historyAnswer').textContent=e.message}};
$('historySearch').onclick=()=>searchPast().catch(e=>$('historyAnswer').textContent=e.message);$('historyMore').onclick=()=>searchPast(false).catch(e=>$('historyAnswer').textContent=e.message);
$('searchButton').onclick=()=>refresh().catch(e=>$('status').textContent=e.message);$('search').onkeydown=e=>{if(e.key==='Enter')$('searchButton').click()};$('clearSearch').onclick=()=>{$('search').value='';$('searchButton').click()};
$('intakeSave').onclick=async()=>{const b=$('intakeSave');b.disabled=true;try{if(!$('intakeTitle').value.trim())throw new Error('案件名を入力してください。');intakeRequestId ||= crypto.randomUUID();const d=await api('intake',{requestId:intakeRequestId,title:$('intakeTitle').value.trim(),channel:$('intakeChannel').value,name:$('intakeName').value.trim(),phone:$('intakePhone').value.trim(),memo:$('intakeMemo').value.trim()});intakeRequestId=null;for(const id of ['intakeTitle','intakeName','intakePhone','intakeMemo'])$(id).value='';$('status').textContent='カルテを作成しました。電話・来店の注文はLINE送信されません。';await refresh();await show(d.orderId)}catch(e){if(e.message.includes('同じ受付番号')||e.message.includes('受付番号が重複'))intakeRequestId=null;$('status').textContent=e.message}finally{b.disabled=false}};
async function show(orderId){selected=orderId;const d=await api('order?id='+encodeURIComponent(orderId));const root=$('detail');root.replaceChildren();const c=el('section');c.append(el('h2',d.order.title),el('div',orderId,'muted'));const dl=el('dl');for(const f of d.fields){dl.append(el('dt',labels[f.field_key]||f.field_key));const dd=el('dd',f.value_text+'（'+(f.status==='confirmed'?'店長確認済み':f.status==='undecided'?'未定':'確認前')+'）');dd.append(button('この内容で確定',()=>command('項目確定 '+orderId+' '+f.field_key+'：'+f.value_text)));dl.append(dd)}c.append(dl,fieldEditor(orderId,d.fields));for(const item of d.items)c.append(el('p',item.label+'：'+item.specification,'stack'));const item=el('textarea');item.placeholder='個別商品例：RINO：背番号1・赤ハート・英語8番';item.setAttribute('aria-label','個別商品の内容');c.append(item,button('個別商品を記録',()=>command('明細 '+orderId+' '+item.value)));for(const change of d.changes){const box=el('div',undefined,'warn');box.append(el('p',(labels[change.field_key]||change.field_key)+'：'+change.old_value+' → '+change.new_value),button('変更を承認',()=>command('変更承認 '+change.id)),button('変更しない',()=>command('変更却下 '+change.id)));c.append(box)}root.append(c);if(d.pastInfo){const past=el('section');past.append(el('h2','リピーターの過去情報（今回未確定）'),el('p',d.pastInfo,'stack'));root.append(past)}for(const draft of d.drafts.filter(x=>['pending','held'].includes(x.status))){const card=el('section');card.append(el('h2','お客様への返信案'));const area=el('textarea');area.value=draft.message;area.setAttribute('aria-label','返信案の本文');card.append(area,button('修正文を保存',()=>command('返信修正 '+draft.id+' '+area.value)),button('保存済みの案を承認送信',async()=>{if(area.value!==draft.message)throw new Error('変更した文章を先に保存してください。');await command('承認送信 '+draft.id)}),button('保留',()=>command('返信保留 '+draft.id)),button('不要な案を取消',()=>command('返信取消 '+draft.id)));root.append(card)}const operations=el('section');operations.append(el('h2','進み具合を記録'));for(const action of ['制作開始','完成','受渡完了','支払案内済み','支払確認待ち','支払完了','回収必要','回収完了','案件終了'])operations.append(button(action,()=>command(action+' '+orderId)));const reply=el('textarea');reply.setAttribute('aria-label','新しい返信文');reply.placeholder='新しい返信文';operations.append(reply,button('返信案を作成',()=>command('返信作成 '+orderId+' '+reply.value)));const memo=el('textarea');memo.setAttribute('aria-label','電話や来店のメモ');memo.placeholder='電話・来店で確認したこと';operations.append(memo,button('メモを保存',()=>command('電話メモ '+orderId+' '+memo.value)));root.append(operations);const history=el('section');history.append(el('h2','会話の根拠（直近100件）'));for(const e of d.events)history.append(el('p',new Date(e.occurred_at).toLocaleString('ja-JP')+' '+({customer:'お客様',owner:'店長',assistant:'送信文',system:'記録'}[e.direction]||e.direction)+'\n'+e.text+(e.media_message_id?'\n画像の内容は原トークで確認してください。':''),'stack'));root.append(history)}
async function showImports(){const d=await api('imports');$('importList').replaceChildren();for(const row of d.imports){const box=el('section');box.append(el('strong',row.source_heading),el('p','確認状態：'+row.review_status,'muted'),button('選択中のお客様へ紐付け',async()=>{if(!selected)throw new Error('先に注文を選んでください。');await command('履歴紐付 '+selected+' '+row.id)}),button('本文を確認した履歴を承認',async()=>{if(!selected)throw new Error('先に注文を選んでください。');await command('履歴承認 '+selected+' '+row.id);await showImports()}));$('importList').append(box)}}
$('connect').onclick=async()=>{key=$('token').value;$('token').value='';try{await refresh();$('login').classList.add('hidden');$('app').classList.remove('hidden');$('logout').classList.remove('hidden')}catch(e){key='';$('status').textContent=e.message}};$('logout').onclick=()=>{key='';location.reload()};$('refresh').onclick=()=>refresh().catch(e=>$('status').textContent=e.message);$('importToggle').onclick=()=>{$('imports').classList.toggle('hidden');showImports().catch(e=>$('status').textContent=e.message)};$('upload').onclick=async()=>{try{const file=$('bundle').files[0];if(!file)throw new Error('取込資料を選んでください。');const data=await api('import',JSON.parse(await file.text()));$('status').textContent=data.staged+'件を確認待ちとして取り込みました。';await showImports()}catch(e){$('status').textContent=e.message}};
const originalShow=show;show=async function(orderId){await originalShow(orderId);document.body.dataset.view='detail';window.scrollTo({top:0,behavior:'smooth'})};
$('navOrders').onclick=()=>{document.body.dataset.view='orders';window.scrollTo({top:0,behavior:'smooth'})};$('navTasks').onclick=()=>{document.body.dataset.view='orders';$('tasks').scrollIntoView({behavior:'smooth'})};$('navDetail').onclick=()=>{if(selected){document.body.dataset.view='detail';window.scrollTo({top:0,behavior:'smooth'})}else{$('status').textContent='先に注文を選んでください。'}};
$('logout').onclick=async()=>{try{await api('logout',{})}finally{key='';location.reload()}};
let installEvent;window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();installEvent=event;$('install').classList.remove('hidden')});$('install').onclick=async()=>{if(installEvent){await installEvent.prompt();installEvent=null;$('install').classList.add('hidden')}};
window.addEventListener('offline',()=>{$('status').textContent='通信が切れました。表示中の情報は最新ではない可能性があります。接続が戻ってから更新してください。'});
window.addEventListener('online',()=>{$('status').textContent='通信が戻りました。最新の状態に更新してください。'});
if('serviceWorker' in navigator)navigator.serviceWorker.register('/manager-sw.js',{scope:'/manager'}).catch(()=>{});
(async()=>{const token=new URLSearchParams(location.hash.slice(1)).get('login');if(token)history.replaceState(null,'',location.pathname);try{if(token)await api('session',{token});await refresh();$('login').classList.add('hidden');$('app').classList.remove('hidden');$('logout').classList.remove('hidden')}catch(error){if(token)$('status').textContent=error.message}})();
</script></html>`;
